[2024-01-21T21:55:57.299+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion.load_data manual__2024-01-21T21:55:53.624677+00:00 [queued]>
[2024-01-21T21:55:57.302+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion.load_data manual__2024-01-21T21:55:53.624677+00:00 [queued]>
[2024-01-21T21:55:57.302+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-01-21T21:55:57.307+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): load_data> on 2024-01-21 21:55:53.624677+00:00
[2024-01-21T21:55:57.310+0000] {standard_task_runner.py:57} INFO - Started process 1067 to run task
[2024-01-21T21:55:57.311+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion', 'load_data', 'manual__2024-01-21T21:55:53.624677+00:00', '--job-id', '339', '--raw', '--subdir', 'DAGS_FOLDER/fetch-api-data.py', '--cfg-path', '/tmp/tmpao5lgfiw']
[2024-01-21T21:55:57.313+0000] {standard_task_runner.py:85} INFO - Job 339: Subtask load_data
[2024-01-21T21:55:57.331+0000] {task_command.py:416} INFO - Running <TaskInstance: data_ingestion.load_data manual__2024-01-21T21:55:53.624677+00:00 [running]> on host 913a57d7b377
[2024-01-21T21:55:57.401+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-21T21:55:53.624677+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-21T21:55:53.624677+00:00'
[2024-01-21T21:55:57.402+0000] {logging_mixin.py:154} INFO - connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
[2024-01-21T21:55:57.402+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-21T21:55:57.405+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_ingestion, task_id=load_data, execution_date=20240121T215553, start_date=20240121T215557, end_date=20240121T215557
[2024-01-21T21:55:57.446+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-21T21:55:57.453+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
