[2024-03-13T16:29:20.661+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion.load_data scheduled__2024-03-12T09:00:00+00:00 [queued]>
[2024-03-13T16:29:20.665+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion.load_data scheduled__2024-03-12T09:00:00+00:00 [queued]>
[2024-03-13T16:29:20.665+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-03-13T16:29:20.670+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): load_data> on 2024-03-12 09:00:00+00:00
[2024-03-13T16:29:20.675+0000] {standard_task_runner.py:57} INFO - Started process 559 to run task
[2024-03-13T16:29:20.677+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion', 'load_data', 'scheduled__2024-03-12T09:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/fetch-api-data.py', '--cfg-path', '/tmp/tmp_q9g4dje']
[2024-03-13T16:29:20.680+0000] {standard_task_runner.py:85} INFO - Job 8: Subtask load_data
[2024-03-13T16:29:20.720+0000] {task_command.py:416} INFO - Running <TaskInstance: data_ingestion.load_data scheduled__2024-03-12T09:00:00+00:00 [running]> on host 5903490e815f
[2024-03-13T16:29:20.823+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-03-12T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-12T09:00:00+00:00'
[2024-03-13T16:29:20.828+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-03-13T16:29:20.838+0000] {logging_mixin.py:154} INFO - Table created successfully or already exists
[2024-03-13T16:29:20.841+0000] {logging_mixin.py:154} INFO - Data inserted successfully
[2024-03-13T16:29:20.841+0000] {logging_mixin.py:154} INFO - PostgreSQL connection closed
[2024-03-13T16:29:20.842+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-03-13T16:29:20.845+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_ingestion, task_id=load_data, execution_date=20240312T090000, start_date=20240313T162920, end_date=20240313T162920
[2024-03-13T16:29:20.859+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-03-13T16:29:20.869+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-13T19:50:57.288+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion.load_data scheduled__2024-03-12T09:00:00+00:00 [queued]>
[2024-03-13T19:50:57.324+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion.load_data scheduled__2024-03-12T09:00:00+00:00 [queued]>
[2024-03-13T19:50:57.325+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-03-13T19:50:57.341+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): load_data> on 2024-03-12 09:00:00+00:00
[2024-03-13T19:50:57.348+0000] {standard_task_runner.py:57} INFO - Started process 311 to run task
[2024-03-13T19:50:57.353+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion', 'load_data', 'scheduled__2024-03-12T09:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/fetch-api-data.py', '--cfg-path', '/tmp/tmpw2jrul3h']
[2024-03-13T19:50:57.355+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask load_data
[2024-03-13T19:50:57.410+0000] {task_command.py:416} INFO - Running <TaskInstance: data_ingestion.load_data scheduled__2024-03-12T09:00:00+00:00 [running]> on host e968ae294a0c
[2024-03-13T19:50:57.547+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-03-12T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-12T09:00:00+00:00'
[2024-03-13T19:50:57.563+0000] {logging_mixin.py:154} INFO - Error while connecting to PostgreSQL The conn_id `postgres_conn` isn't defined
[2024-03-13T19:50:57.564+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-03-13T19:50:57.591+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_ingestion, task_id=load_data, execution_date=20240312T090000, start_date=20240313T195057, end_date=20240313T195057
[2024-03-13T19:50:57.619+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-03-13T19:50:57.646+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
