[2024-03-26T16:13:35.381+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion.load_data manual__2024-03-26T16:13:30.298980+00:00 [queued]>
[2024-03-26T16:13:35.385+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion.load_data manual__2024-03-26T16:13:30.298980+00:00 [queued]>
[2024-03-26T16:13:35.385+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-03-26T16:13:35.390+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): load_data> on 2024-03-26 16:13:30.298980+00:00
[2024-03-26T16:13:35.394+0000] {standard_task_runner.py:57} INFO - Started process 525 to run task
[2024-03-26T16:13:35.396+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion', 'load_data', 'manual__2024-03-26T16:13:30.298980+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/fetch-api-data.py', '--cfg-path', '/tmp/tmprht9_zga']
[2024-03-26T16:13:35.399+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask load_data
[2024-03-26T16:13:35.424+0000] {task_command.py:416} INFO - Running <TaskInstance: data_ingestion.load_data manual__2024-03-26T16:13:30.298980+00:00 [running]> on host b3a14f9969c8
[2024-03-26T16:13:35.523+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-03-26T16:13:30.298980+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-26T16:13:30.298980+00:00'
[2024-03-26T16:13:35.529+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-03-26T16:13:35.538+0000] {logging_mixin.py:154} INFO - Error while connecting to PostgreSQL duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(public_holiday, 2200) already exists.
[2024-03-26T16:13:35.539+0000] {logging_mixin.py:154} INFO - Data inserted successfully
[2024-03-26T16:13:35.539+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-03-26T16:13:35.546+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_ingestion, task_id=load_data, execution_date=20240326T161330, start_date=20240326T161335, end_date=20240326T161335
[2024-03-26T16:13:35.575+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-03-26T16:13:35.591+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
